# Generated by Django 3.2.25 on 2024-08-25 17:00

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import webstack.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstLevelMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('code', models.SlugField(default=webstack.models.generate_id, unique=True)),
                ('icon', models.CharField(help_text='Font Awesome图标库格式，如:fa fa-star-o', max_length=100, verbose_name='图标')),
                ('sort', models.IntegerField(default=100, help_text='自定义顺序', verbose_name='顺序')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '一级菜单项',
                'verbose_name_plural': '一级菜单项',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='SecondLevelMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('code', models.SlugField(default=webstack.models.generate_id, unique=True)),
                ('icon', models.CharField(help_text='Font Awesome图标库格式，如:fa fa-star-o', max_length=100, verbose_name='图标')),
                ('sort', models.IntegerField(default=100, help_text='自定义顺序', verbose_name='顺序')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='second_level_menus', to='webstack.firstlevelmenuitem', verbose_name='父级菜单')),
            ],
            options={
                'verbose_name': '二级菜单项',
                'verbose_name_plural': '二级菜单项',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='WebStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='名称')),
                ('description', models.TextField(max_length=100, verbose_name='描述')),
                ('url', models.URLField(verbose_name='网站地址')),
                ('image', imagekit.models.fields.ProcessedImageField(default='web/default/default.png', help_text='上传图片大小建议使用1:1的宽高比，为了清晰度原始图片宽度应该超过50px', upload_to='web/upload/%Y/%m/%d/', verbose_name='Logo图片')),
                ('sort', models.IntegerField(default=100, help_text='自定义顺序', verbose_name='顺序')),
                ('enable_use', models.BooleanField(blank=True, default=True, null=True, verbose_name='是否可用')),
                ('disable_use_reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='不可用原因')),
                ('is_show', models.BooleanField(blank=True, default=True, null=True, verbose_name='是否展示')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webstack_list', to='webstack.secondlevelmenuitem', verbose_name='所属二级菜单')),
            ],
            options={
                'verbose_name': '网站',
                'verbose_name_plural': '网站',
                'ordering': ['sort'],
            },
        ),
    ]
